/**
 * Find the exact 8-byte difference between Rust CSR and TypeScript SDK CSR
 */

const path = require('path');

// Load TypeScript SDK
let Utils, ProtoWallet, Random, sdk, Mnemonic, HD, MasterCertificate;
try {
    const sdkPath = path.join(__dirname, '..', 'reference', 'ts-brc100', 'node_modules', '@bsv', 'sdk');
    sdk = require(sdkPath);
    Utils = sdk.Utils || sdk;
    MasterCertificate = sdk.MasterCertificate;
    ProtoWallet = sdk.ProtoWallet;
    Random = sdk.Random;

    const compatPath = path.join(__dirname, '..', 'reference', 'ts-brc100', 'node_modules', '@bsv', 'sdk', 'dist', 'cjs', 'src', 'compat');
    const MnemonicModule = require(path.join(compatPath, 'Mnemonic.js'));
    Mnemonic = MnemonicModule.default || MnemonicModule;
    const HDModule = require(path.join(compatPath, 'HD.js'));
    HD = HDModule.default || HDModule;
} catch (error) {
    console.error('Failed to load TypeScript SDK:', error.message);
    process.exit(1);
}

// Rust CSR from logs
const rustCSR = '{"clientNonce":"AcOe0trPxD412BQ9v07MbIHm0U3AUMUFlAwGaIaAeG4=","type":"AGfk/WrT1eBDXpz3mcw386Zww2HmqcIn3uY6x4Af1eo=","fields":{"cool":"fDWhzA+0jwMD7GiZ/laOE8pJWhprxnxNFkMwoSeVSNa8YN8mkRAvfAEO526QWvp7y8f3bQ=="},"masterKeyring":{"cool":"cyoejQMHjaBoyiQLI9iqNVOEeZ4ZpVrnSks6mO93CJQuXnzkrQYbj2iuhCzpQqkqTU31Y/bt/JYc98EMISx7IP3jm83/9bb2UV4XUda3Yy0="}}';

async function findDifference() {
    console.log('🔍 Finding CSR Difference');
    console.log('='.repeat(70));
    console.log('');

    // Parse Rust CSR
    const rustCSRParsed = JSON.parse(rustCSR);
    const rustCSRBytes = Buffer.from(rustCSR, 'utf8');

    console.log('📋 Rust CSR:');
    console.log(`   Length: ${rustCSRBytes.length} bytes`);
    console.log(`   JSON: ${rustCSR}`);
    console.log('');

    // Extract values from Rust CSR
    const clientNonce = rustCSRParsed.clientNonce;
    const type = rustCSRParsed.type;
    const certifier = '0220529dc803041a83f4357864a09c717daa24397cf2f3fc3a5745ae08d30924fd';
    const fields = { cool: 'true' };  // The plaintext value

    console.log('📋 Inputs (from Rust CSR):');
    console.log(`   clientNonce: ${clientNonce}`);
    console.log(`   type: ${type}`);
    console.log(`   certifier: ${certifier}`);
    console.log(`   fields: ${JSON.stringify(fields)}`);
    console.log('');

    // Create wallet (using same mnemonic for reproducibility)
    const mnemonicStr = 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
    const mnemonic = new Mnemonic(mnemonicStr);
    mnemonic.mnemonic2Seed();
    const hdWallet = HD.fromSeed(mnemonic.seed);
    const wallet = new ProtoWallet(hdWallet.privKey);

    console.log('🔧 Generating TypeScript SDK CSR...');
    console.log('');

    // Create certificate fields and masterKeyring
    // NOTE: We can't use the same clientNonce because it's generated by the wallet
    // But we can compare the structure
    const { certificateFields, masterKeyring } = await MasterCertificate.createCertificateFields(
        wallet,
        certifier,
        fields
    );

    // Get clientNonce (TypeScript SDK generates it)
    const tsClientNonce = await sdk.createNonce(wallet, certifier);

    // Build CSR JSON
    const tsCSR = {
        clientNonce: tsClientNonce,
        type: type,
        fields: certificateFields,
        masterKeyring: masterKeyring
    };

    const tsCSRString = JSON.stringify(tsCSR);
    const tsCSRBytes = Buffer.from(tsCSRString, 'utf8');

    console.log('📋 TypeScript SDK CSR:');
    console.log(`   Length: ${tsCSRBytes.length} bytes`);
    console.log(`   JSON: ${tsCSRString}`);
    console.log('');

    // Compare lengths
    const lengthDiff = tsCSRBytes.length - rustCSRBytes.length;
    console.log('📊 Length Comparison:');
    console.log(`   Rust: ${rustCSRBytes.length} bytes`);
    console.log(`   TypeScript: ${tsCSRBytes.length} bytes`);
    console.log(`   Difference: ${lengthDiff} bytes`);
    console.log('');

    // Compare structure
    console.log('📊 Structure Comparison:');
    console.log(`   Rust clientNonce length: ${rustCSRParsed.clientNonce.length} chars`);
    console.log(`   TS clientNonce length: ${tsCSR.clientNonce.length} chars`);
    console.log(`   Rust type length: ${rustCSRParsed.type.length} chars`);
    console.log(`   TS type length: ${tsCSR.type.length} chars`);
    console.log(`   Rust fields.cool length: ${rustCSRParsed.fields.cool.length} chars`);
    console.log(`   TS fields.cool length: ${tsCSR.fields.cool.length} chars`);
    console.log(`   Rust masterKeyring.cool length: ${rustCSRParsed.masterKeyring.cool.length} chars`);
    console.log(`   TS masterKeyring.cool length: ${tsCSR.masterKeyring.cool.length} chars`);
    console.log('');

    // Compare field order
    console.log('📊 Field Order Comparison:');
    const rustKeys = Object.keys(rustCSRParsed);
    const tsKeys = Object.keys(tsCSR);
    console.log(`   Rust order: ${rustKeys.join(' -> ')}`);
    console.log(`   TS order: ${tsKeys.join(' -> ')}`);
    console.log(`   Order matches: ${JSON.stringify(rustKeys) === JSON.stringify(tsKeys)}`);
    console.log('');

    // Compare nested object keys
    console.log('📊 Nested Object Keys:');
    const rustFieldsKeys = Object.keys(rustCSRParsed.fields);
    const tsFieldsKeys = Object.keys(tsCSR.fields);
    console.log(`   Rust fields keys: ${rustFieldsKeys.join(', ')}`);
    console.log(`   TS fields keys: ${tsFieldsKeys.join(', ')}`);
    console.log(`   Fields keys match: ${JSON.stringify(rustFieldsKeys) === JSON.stringify(tsFieldsKeys)}`);

    const rustMKKeys = Object.keys(rustCSRParsed.masterKeyring);
    const tsMKKeys = Object.keys(tsCSR.masterKeyring);
    console.log(`   Rust masterKeyring keys: ${rustMKKeys.join(', ')}`);
    console.log(`   TS masterKeyring keys: ${tsMKKeys.join(', ')}`);
    console.log(`   MasterKeyring keys match: ${JSON.stringify(rustMKKeys) === JSON.stringify(tsMKKeys)}`);
    console.log('');

    // Byte-by-byte comparison (if same length)
    if (rustCSRBytes.length === tsCSRBytes.length) {
        console.log('📊 Byte-by-byte Comparison:');
        let firstDiff = -1;
        for (let i = 0; i < rustCSRBytes.length; i++) {
            if (rustCSRBytes[i] !== tsCSRBytes[i]) {
                firstDiff = i;
                break;
            }
        }
        if (firstDiff >= 0) {
            console.log(`   First difference at byte ${firstDiff}`);
            console.log(`   Rust byte: 0x${rustCSRBytes[firstDiff].toString(16)} (${String.fromCharCode(rustCSRBytes[firstDiff])})`);
            console.log(`   TS byte:   0x${tsCSRBytes[firstDiff].toString(16)} (${String.fromCharCode(tsCSRBytes[firstDiff])})`);
        } else {
            console.log('   ✅ CSRs are identical!');
        }
    } else {
        console.log('📊 Length Difference Analysis:');
        console.log(`   The CSRs have different lengths, so they differ in content.`);
        console.log(`   This is expected because:`);
        console.log(`   - Different clientNonces (random)`);
        console.log(`   - Different encrypted values (different IVs/keys)`);
        console.log('');
        console.log('📊 What SHOULD be the same:');
        console.log(`   - Field order: ${JSON.stringify(rustKeys) === JSON.stringify(tsKeys) ? '✅' : '❌'}`);
        console.log(`   - Fields object key order: ${JSON.stringify(rustFieldsKeys) === JSON.stringify(tsFieldsKeys) ? '✅' : '❌'}`);
        console.log(`   - MasterKeyring object key order: ${JSON.stringify(rustMKKeys) === JSON.stringify(tsMKKeys) ? '✅' : '❌'}`);
        console.log(`   - Type value: ${rustCSRParsed.type === tsCSR.type ? '✅' : '❌'}`);
        console.log('');
        console.log('📊 What WILL be different (expected):');
        console.log(`   - clientNonce: Different (random)`);
        console.log(`   - Encrypted field values: Different (different IVs/keys)`);
        console.log(`   - Encrypted masterKeyring values: Different (different IVs/keys)`);
    }

    console.log('');
    console.log('='.repeat(70));
}

findDifference().catch(error => {
    console.error('❌ Error:', error);
    console.error(error.stack);
    process.exit(1);
});
