//! Interoperability test between Rust and TypeScript SDK
//!
//! This test verifies that our Rust implementation can decrypt data encrypted by the TypeScript SDK,
//! and vice versa. This helps identify any subtle differences in encryption implementation.
//!
//! To use this test:
//! 1. Run the TypeScript test script to generate test vectors: `node test_interoperability_ts.js`
//! 2. Run this Rust test: `cargo test interoperability_test -- --nocapture`

use hex;
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use rand::RngCore;
use hodos_wallet::brc2;
use hodos_wallet::aesgcm_custom;

#[test]
fn test_decrypt_typescript_encrypted_field() {
    // This test uses data encrypted by TypeScript SDK
    // The test vectors are generated by running the TypeScript test script

    // Example: Field value "true" encrypted by TypeScript SDK
    // These values should be generated by the TypeScript test script
    let ts_encrypted_base64 = "9ycH95dRjW8wF0G9pxajU/RsfOE47Si7+Fg/KsD2ghMhyWtmvPRqOqPPGNQYRrrBWUuycw==";

    // Decode from base64
    let ts_encrypted = BASE64.decode(ts_encrypted_base64).unwrap();

    // Extract components: [32-byte IV][ciphertext][16-byte auth tag]
    assert!(ts_encrypted.len() >= 48, "Encrypted data too short");
    let iv = &ts_encrypted[0..32];
    let ciphertext = &ts_encrypted[32..ts_encrypted.len() - 16];
    let auth_tag = &ts_encrypted[ts_encrypted.len() - 16..];

    // For this test, we need the symmetric key that was used
    // In a real scenario, this would be derived using BRC-42
    // For now, we'll use a known key from our logs
    let symmetric_key = hex::decode("144b197ff853375c898f9663c795dbba45f4d959ad1d9d2e2cabd030dde07130").unwrap();
    let key_array: [u8; 32] = symmetric_key.try_into().unwrap();

    // Try to decrypt using our Rust implementation
    let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
        ciphertext,
        &[],  // Additional authenticated data (empty for BRC-2)
        iv,
        auth_tag,
        &key_array,
    );

    match decrypted {
        Ok(plaintext) => {
            let plaintext_str = String::from_utf8(plaintext.clone()).unwrap();
            println!("✅ Successfully decrypted TypeScript-encrypted data!");
            println!("   Plaintext: {}", plaintext_str);
            println!("   Plaintext (hex): {}", hex::encode(&plaintext));
            assert_eq!(plaintext, b"true", "Decrypted plaintext doesn't match expected 'true'");
        }
        Err(e) => {
            panic!("❌ Failed to decrypt TypeScript-encrypted data: {}", e);
        }
    }
}

#[test]
fn test_encrypt_for_typescript_decryption() {
    // This test encrypts data in Rust and verifies the format matches TypeScript SDK
    // The encrypted data can then be tested with TypeScript SDK for decryption

    let plaintext = b"true";
    let symmetric_key = hex::decode("42b79dacfdca814a26a29522c53a50923574bf98c13cbaa5709053b71492e52b").unwrap();
    let key_array: [u8; 32] = symmetric_key.try_into().unwrap();

    // Generate random IV (32 bytes)
    let mut iv = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut iv);

    // Encrypt using our Rust implementation
    let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
        plaintext,
        &[],  // Additional authenticated data (empty for BRC-2)
        &iv,
        &key_array,
    ).unwrap();

    // Format: [32-byte IV][ciphertext][16-byte auth tag]
    let mut encrypted = iv.to_vec();
    encrypted.extend_from_slice(&ciphertext);
    encrypted.extend_from_slice(&auth_tag);

    // Base64 encode (matching TypeScript SDK format)
    let encrypted_base64 = BASE64.encode(&encrypted);

    println!("✅ Encrypted data in Rust (ready for TypeScript decryption):");
    println!("   Base64: {}", encrypted_base64);
    println!("   IV (hex): {}", hex::encode(&iv));
    println!("   Ciphertext (hex): {}", hex::encode(&ciphertext));
    println!("   Auth tag (hex): {}", hex::encode(&auth_tag));
    println!("   Total length: {} bytes", encrypted.len());

    // Verify we can decrypt our own encryption (roundtrip test)
    let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
        &ciphertext,
        &[],
        &iv,
        &auth_tag,
        &key_array,
    ).unwrap();

    assert_eq!(plaintext, decrypted.as_slice(), "Roundtrip decryption failed");
    println!("   ✅ Roundtrip test passed (can decrypt our own encryption)");
}

#[test]
fn test_brc2_field_encryption_interoperability() {
    // Test BRC-2 field encryption (full flow with BRC-42 key derivation)
    // This requires actual private/public keys

    // Use test keys (these should match the TypeScript test)
    let sender_private_key = hex::decode("6a2991c9de20e38b31d7ea147bf55f5039e4bbc073160f5e0d541d1f17e321b8").unwrap();
    let recipient_public_key = hex::decode("0294c479f762f6baa97fbcd4393564c1d7bd8336ebd15928135bbcf575cd1a71a1").unwrap();
    let field_name = "cool";

    // Encrypt field value using BRC-2
    let plaintext = b"true";
    let encrypted = brc2::encrypt_certificate_field(
        &sender_private_key,
        &recipient_public_key,
        field_name,
        None,  // No serialNumber for master keyring
        plaintext,
    ).unwrap();

    println!("✅ BRC-2 field encryption (Rust):");
    println!("   Encrypted length: {} bytes", encrypted.len());
    println!("   Encrypted (base64): {}", BASE64.encode(&encrypted));
    println!("   Encrypted (hex, first 64): {}", hex::encode(&encrypted[..encrypted.len().min(64)]));

    // Verify format: [32-byte IV][ciphertext][16-byte auth tag]
    assert!(encrypted.len() >= 48, "Encrypted data too short");
    let iv = &encrypted[0..32];
    let ciphertext = &encrypted[32..encrypted.len() - 16];
    let auth_tag = &encrypted[encrypted.len() - 16..];

    println!("   IV (hex): {}", hex::encode(iv));
    println!("   Ciphertext length: {} bytes", ciphertext.len());
    println!("   Auth tag (hex): {}", hex::encode(auth_tag));

    // Try to decrypt using BRC-2
    let decrypted = brc2::decrypt_certificate_field(
        &sender_private_key,  // In real scenario, this would be recipient's private key
        &recipient_public_key, // In real scenario, this would be sender's public key
        field_name,
        None,
        &encrypted,
    );

    match decrypted {
        Ok(plaintext_decrypted) => {
            let plaintext_str = String::from_utf8(plaintext_decrypted.clone()).unwrap();
            println!("   ✅ Decryption successful!");
            println!("   Decrypted: {}", plaintext_str);
            assert_eq!(plaintext, plaintext_decrypted.as_slice());
        }
        Err(e) => {
            println!("   ⚠️  Decryption failed (this is expected if using wrong keys): {}", e);
            // This is expected if we're using the wrong keys for decryption
            // In a real scenario, the recipient would use their private key
        }
    }
}

#[test]
fn test_revelation_key_stripping() {
    // Test that our revelation key stripping matches TypeScript SDK's toArray() behavior

    // Test case 1: Key with leading zeros
    let key_with_zeros = vec![0x00, 0x00, 0x01, 0x02, 0x03];
    let stripped = strip_leading_zeros(&key_with_zeros);
    println!("Key with leading zeros: {:?}", key_with_zeros);
    println!("Stripped: {:?}", stripped);
    assert_eq!(stripped, vec![0x01, 0x02, 0x03], "Failed to strip leading zeros");

    // Test case 2: Key with no leading zeros
    let key_no_zeros = vec![0x01, 0x02, 0x03];
    let stripped2 = strip_leading_zeros(&key_no_zeros);
    assert_eq!(stripped2, key_no_zeros, "Should not modify key without leading zeros");

    // Test case 3: Key that's all zeros (should return [0])
    let key_all_zeros = vec![0x00, 0x00, 0x00];
    let stripped3 = strip_leading_zeros(&key_all_zeros);
    assert_eq!(stripped3, vec![0x00], "All zeros should return [0]");

    // Test case 4: Single zero byte
    let key_single_zero = vec![0x00];
    let stripped4 = strip_leading_zeros(&key_single_zero);
    assert_eq!(stripped4, vec![0x00], "Single zero should return [0]");

    println!("✅ Revelation key stripping tests passed!");
}

/// Strip leading zeros from a byte array, matching TypeScript SDK's toArray() behavior
/// Returns at least 1 byte (if all zeros, returns [0])
fn strip_leading_zeros(bytes: &[u8]) -> Vec<u8> {
    let mut stripped = bytes.to_vec();
    // Remove leading zeros, but keep at least 1 byte
    while stripped.len() > 1 && stripped[0] == 0 {
        stripped.remove(0);
    }
    stripped
}
