//! PushDrop cross-implementation tests
//!
//! These tests use test vectors generated by the TypeScript SDK
//! to validate our Rust implementation without circular validation.

#[cfg(test)]
mod cross_validation_tests {
    use crate::script::pushdrop::decode;
    use std::fs;

    /// Load test vectors from JSON file generated by TypeScript SDK
    fn load_test_vectors() -> Result<Vec<serde_json::Value>, Box<dyn std::error::Error>> {
        let test_vectors_path = "pushdrop_test_vectors.json";
        let content = fs::read_to_string(test_vectors_path)?;
        let vectors: Vec<serde_json::Value> = serde_json::from_str(&content)?;
        Ok(vectors)
    }

    /// Test decoding TypeScript-generated scripts
    #[test]
    #[ignore] // Only run when test vectors are available
    fn test_decode_typescript_scripts() {
        let vectors = match load_test_vectors() {
            Ok(v) => v,
            Err(_) => {
                println!("⚠️  Test vectors not found. Run test_pushdrop_cross_validation.ps1 first.");
                return;
            }
        };

        for vector in vectors {
            if vector["error"].is_string() {
                println!("⚠️  Skipping test case with error: {}", vector["name"]);
                continue;
            }

            let name = vector["name"].as_str().unwrap();
            let script_hex = vector["scriptHex"].as_str().unwrap();
            let expected_pubkey_hex = vector["publicKeyHex"].as_str().unwrap();
            let expected_fields: Vec<Vec<u8>> = vector["fields"]
                .as_array()
                .unwrap()
                .iter()
                .map(|f| {
                    f.as_array()
                        .unwrap()
                        .iter()
                        .map(|b| b.as_u64().unwrap() as u8)
                        .collect()
                })
                .collect();

            // Decode script
            let script_bytes = hex::decode(script_hex).unwrap();
            let decoded = decode(&script_bytes).unwrap();

            // Verify public key
            let expected_pubkey = hex::decode(expected_pubkey_hex).unwrap();
            assert_eq!(
                decoded.locking_public_key,
                expected_pubkey,
                "Public key mismatch in test case: {}",
                name
            );

            // Verify fields
            assert_eq!(
                decoded.fields.len(),
                expected_fields.len(),
                "Field count mismatch in test case: {}",
                name
            );

            for (i, (decoded_field, expected_field)) in
                decoded.fields.iter().zip(expected_fields.iter()).enumerate()
            {
                assert_eq!(
                    decoded_field, expected_field,
                    "Field {} mismatch in test case: {}",
                    i, name
                );
            }

            println!("✅ Test case passed: {}", name);
        }
    }
}

#[cfg(test)]
mod bitcoin_standard_tests {
    //! Tests against Bitcoin script standards (no circular validation)

    use crate::script::parser::{parse_script_chunks, opcodes};
    use crate::script::pushdrop::create_minimally_encoded_chunk;

    #[test]
    fn test_opcode_parsing_standard() {
        // OP_0 is well-defined Bitcoin opcode
        let script = vec![opcodes::OP_0];
        let chunks = parse_script_chunks(&script).unwrap();
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].op, opcodes::OP_0);
        assert_eq!(chunks[0].data, None);
    }

    #[test]
    fn test_op_1_through_16_standard() {
        // OP_1 through OP_16 are well-defined Bitcoin opcodes
        for i in 1..=16 {
            let opcode = 0x50 + i;
            let script = vec![opcode];
            let chunks = parse_script_chunks(&script).unwrap();
            assert_eq!(chunks.len(), 1);
            assert_eq!(chunks[0].op, opcode);
            assert_eq!(chunks[0].data, None);
        }
    }

    #[test]
    fn test_pushdata1_standard() {
        // OP_PUSHDATA1 format is well-documented Bitcoin script standard
        let data = vec![0x42; 100];
        let mut script = vec![opcodes::OP_PUSHDATA1, 100];
        script.extend(&data);

        let chunks = parse_script_chunks(&script).unwrap();
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].op, opcodes::OP_PUSHDATA1);
        assert_eq!(chunks[0].data.as_ref().unwrap().len(), 100);
        assert_eq!(chunks[0].data.as_ref().unwrap(), &data);
    }

    #[test]
    fn test_pushdata2_standard() {
        // OP_PUSHDATA2 format is well-documented Bitcoin script standard
        let data = vec![0x42; 300];
        let mut script = vec![opcodes::OP_PUSHDATA2];
        script.extend((300u16).to_le_bytes());
        script.extend(&data);

        let chunks = parse_script_chunks(&script).unwrap();
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].op, opcodes::OP_PUSHDATA2);
        assert_eq!(chunks[0].data.as_ref().unwrap().len(), 300);
        assert_eq!(chunks[0].data.as_ref().unwrap(), &data);
    }

    #[test]
    fn test_minimal_encoding_op_0() {
        // Empty or [0] → OP_0 is a well-known Bitcoin script optimization
        assert_eq!(create_minimally_encoded_chunk(&[]), vec![opcodes::OP_0]);
        assert_eq!(create_minimally_encoded_chunk(&[0]), vec![opcodes::OP_0]);
    }

    #[test]
    fn test_minimal_encoding_op_1_16() {
        // [1-16] → OP_1-OP_16 is a well-known Bitcoin script optimization
        for i in 1..=16 {
            let encoded = create_minimally_encoded_chunk(&[i]);
            assert_eq!(encoded, vec![opcodes::OP_1 + (i - 1)]);
        }
    }

    #[test]
    fn test_minimal_encoding_op_1negate() {
        // [0x81] → OP_1NEGATE is a well-known Bitcoin script optimization
        assert_eq!(
            create_minimally_encoded_chunk(&[0x81]),
            vec![opcodes::OP_1NEGATE]
        );
    }

    #[test]
    fn test_minimal_encoding_length_boundaries() {
        // Test length boundaries for OP_PUSHDATA1/2/4
        // These are well-defined Bitcoin script limits

        // Direct push (length <= 75)
        let data_75 = vec![0x42; 75];
        let encoded = create_minimally_encoded_chunk(&data_75);
        assert_eq!(encoded[0], 75);
        assert_eq!(&encoded[1..], &data_75);

        // OP_PUSHDATA1 (75 < length <= 255)
        let data_200 = vec![0x42; 200];
        let encoded = create_minimally_encoded_chunk(&data_200);
        assert_eq!(encoded[0], opcodes::OP_PUSHDATA1);
        assert_eq!(encoded[1], 200);
        assert_eq!(&encoded[2..], &data_200);

        // OP_PUSHDATA2 (255 < length <= 65535)
        let data_500 = vec![0x42; 500];
        let encoded = create_minimally_encoded_chunk(&data_500);
        assert_eq!(encoded[0], opcodes::OP_PUSHDATA2);
        let length = u16::from_le_bytes([encoded[1], encoded[2]]);
        assert_eq!(length, 500);
        assert_eq!(&encoded[3..], &data_500);
    }
}
