//! Test to verify AESGCM encryption/decryption roundtrip and cross-implementation compatibility
//! with the TypeScript BSV SDK.

#[cfg(test)]
mod tests {
    use crate::crypto::aesgcm_custom;
    use hex;

    #[test]
    fn test_aesgcm_roundtrip_4_bytes() {
        // Test with 4-byte plaintext (like "true")
        let plaintext = b"true";
        let key = [0u8; 32]; // Zero key for testing
        let iv = [0u8; 32]; // Zero IV for testing

        // Encrypt
        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            plaintext,
            &[],
            &iv,
            &key,
        ).unwrap();

        // Decrypt
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &iv,
            &auth_tag,
            &key,
        ).unwrap();

        assert_eq!(plaintext, decrypted.as_slice());
    }

    #[test]
    fn test_aesgcm_roundtrip_32_bytes() {
        // Test with 32-byte plaintext (like a symmetric key)
        let plaintext = [0x42u8; 32];
        let key = [0u8; 32]; // Zero key for testing
        let iv = [0u8; 32]; // Zero IV for testing

        // Encrypt
        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            &plaintext,
            &[],
            &iv,
            &key,
        ).unwrap();

        // Decrypt
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &iv,
            &auth_tag,
            &key,
        ).unwrap();

        assert_eq!(&plaintext, decrypted.as_slice());
    }

    #[test]
    fn test_aesgcm_with_real_values() {
        // Test with values from the logs
        let plaintext = hex::decode("74727565").unwrap(); // "true"
        let key = hex::decode("42b79dacfdca814a26a29522c53a50923574bf98c13cbaa5709053b71492e52b").unwrap();
        let iv = hex::decode("41113d6599ece0d23e9ec3e1e80b168019087a1d2e4e27061de54b4b79f5cb6c").unwrap();

        let key_array: [u8; 32] = key.try_into().unwrap();

        // Encrypt
        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            &plaintext,
            &[],
            &iv,
            &key_array,
        ).unwrap();

        println!("Ciphertext: {}", hex::encode(&ciphertext));
        println!("Auth tag: {}", hex::encode(&auth_tag));

        // Decrypt
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &iv,
            &auth_tag,
            &key_array,
        ).unwrap();

        assert_eq!(plaintext, decrypted);

        // Verify it matches expected from logs
        let expected_ciphertext = hex::decode("0b69b220").unwrap();
        let expected_tag = hex::decode("427c72dce8cdacf6418b9294153ffdfa").unwrap();

        assert_eq!(ciphertext, expected_ciphertext, "Ciphertext mismatch!");
        assert_eq!(auth_tag, expected_tag, "Auth tag mismatch!");
    }

    // =========================================================================
    // Cross-implementation tests: vectors generated by TypeScript BSV SDK
    // See reference/ts-brc100/test-aesgcm-vectors.mjs for the generator script
    // =========================================================================

    #[test]
    fn test_aesgcm_cross_impl_32byte_iv() {
        // Test 1 from TypeScript: AESGCM with 32-byte IV (BRC-2 format)
        // Generated by: AESGCM(plaintext, [], iv, key) from @bsv/sdk
        let key = hex::decode("424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b").unwrap();
        let iv = hex::decode("abb8c5d2dfecf90613202d3a4754616e7b8895a2afbcc9d6e3f0fd0a1724313e").unwrap();
        let plaintext = hex::decode("48656c6c6f204252432d32").unwrap(); // "Hello BRC-2"

        let expected_ct = hex::decode("9d728ba53755f2e92f330e").unwrap();
        let expected_tag = hex::decode("401337c7140d6af2aef1ca916f6b4e67").unwrap();

        let key_array: [u8; 32] = key.try_into().unwrap();

        // Encrypt and compare with TypeScript output
        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            &plaintext,
            &[],
            &iv,
            &key_array,
        ).unwrap();

        assert_eq!(ciphertext, expected_ct,
            "AESGCM 32-byte IV ciphertext mismatch!\n  Rust: {}\n  TypeScript: {}",
            hex::encode(&ciphertext), hex::encode(&expected_ct));
        assert_eq!(auth_tag, expected_tag,
            "AESGCM 32-byte IV auth tag mismatch!\n  Rust: {}\n  TypeScript: {}",
            hex::encode(&auth_tag), hex::encode(&expected_tag));

        // Verify decryption works
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &iv,
            &auth_tag,
            &key_array,
        ).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_aesgcm_cross_impl_12byte_iv() {
        // Test 2 from TypeScript: AESGCM with standard 12-byte IV
        let key = hex::decode("424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b").unwrap();
        let iv12 = hex::decode("abb8c5d2dfecf90613202d3a").unwrap();
        let plaintext = hex::decode("48656c6c6f204252432d32").unwrap(); // "Hello BRC-2"

        let key_array: [u8; 32] = key.try_into().unwrap();

        // Encrypt with 12-byte IV
        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            &plaintext,
            &[],
            &iv12,
            &key_array,
        ).unwrap();

        // Verify roundtrip
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &iv12,
            &auth_tag,
            &key_array,
        ).unwrap();
        assert_eq!(decrypted, plaintext, "12-byte IV roundtrip failed");

        // Note: 12-byte IV produces different ciphertext than 32-byte IV (different J0 derivation)
        let ct_32 = hex::decode("9d728ba53755f2e92f330e").unwrap();
        assert_ne!(ciphertext, ct_32, "12-byte IV should produce different ciphertext than 32-byte IV");
    }

    #[test]
    fn test_brc42_symmetric_key_derivation_and_encrypt() {
        // Test 6 from TypeScript: BRC-42 symmetric key derivation + encryption
        // Uses official BRC-42 test vector keys
        use crate::crypto::brc42::derive_symmetric_key_for_hmac;

        let alice_priv = hex::decode("6a2991c9de20e38b31d7ea147bf55f5039e4bbc073160f5e0d541d1f17e321b8").unwrap();
        let bob_pub = hex::decode("02e28e2d957e38c1b675bf52de0f0d01d41b1f298034ad2954498697708563bf02").unwrap();
        let invoice = "2-certificate field encryption-userName";

        // Expected symmetric key (full 32-byte x-coordinate from TypeScript)
        let expected_sym_key = hex::decode("a8d3aa4317f3f9343f45e348035734130d95d4a7a62af31c7a806c5396e0fb3a").unwrap();

        // Derive symmetric key using BRC-42
        let sym_key = derive_symmetric_key_for_hmac(&alice_priv, &bob_pub, invoice).unwrap();

        assert_eq!(sym_key, expected_sym_key,
            "BRC-42 symmetric key mismatch!\n  Rust: {}\n  TypeScript: {}",
            hex::encode(&sym_key), hex::encode(&expected_sym_key));

        // Now encrypt with the derived key and verify against TypeScript output
        let test_plaintext = "test field value".as_bytes();
        let test_iv = hex::decode("77828d98a3aeb9c4cfdae5f0fb06111c27323d48535e69747f8a95a0abb6c1cc").unwrap();

        let expected_ct = hex::decode("db37561c3708cf0b160c550486ca2825").unwrap();
        let expected_tag = hex::decode("e3e5de2bee5383e669b4d9bca07e66cd").unwrap();

        let key_array: [u8; 32] = sym_key.try_into().unwrap();

        let (ciphertext, auth_tag) = aesgcm_custom::aesgcm_custom(
            test_plaintext,
            &[],
            &test_iv,
            &key_array,
        ).unwrap();

        assert_eq!(ciphertext, expected_ct,
            "BRC-42 derived key encryption ciphertext mismatch!\n  Rust: {}\n  TypeScript: {}",
            hex::encode(&ciphertext), hex::encode(&expected_ct));
        assert_eq!(auth_tag, expected_tag,
            "BRC-42 derived key encryption auth tag mismatch!\n  Rust: {}\n  TypeScript: {}",
            hex::encode(&auth_tag), hex::encode(&expected_tag));

        // Verify decryption
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ciphertext,
            &[],
            &test_iv,
            &auth_tag,
            &key_array,
        ).unwrap();
        assert_eq!(decrypted, test_plaintext);
    }

    #[test]
    fn test_aesgcm_leading_zero_key_roundtrip() {
        // Test 4 from TypeScript: key with leading zero byte
        // Our aesgcm_custom always takes &[u8; 32], so we only test roundtrip
        // (TypeScript's AES left-pads shorter keys internally, but we always pass 32 bytes)
        let key_with_zero = hex::decode("00424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d14").unwrap();
        let iv = hex::decode("abb8c5d2dfecf90613202d3a4754616e7b8895a2afbcc9d6e3f0fd0a1724313e").unwrap();
        let plaintext = hex::decode("48656c6c6f204252432d32").unwrap(); // "Hello BRC-2"

        let key_array: [u8; 32] = key_with_zero.try_into().unwrap();

        // Encrypt with full 32-byte key (including leading zero)
        let (ct_full, tag_full) = aesgcm_custom::aesgcm_custom(
            &plaintext,
            &[],
            &iv,
            &key_array,
        ).unwrap();

        // Verify roundtrip
        let decrypted = aesgcm_custom::aesgcm_decrypt_custom(
            &ct_full,
            &[],
            &iv,
            &tag_full,
            &key_array,
        ).unwrap();
        assert_eq!(decrypted, plaintext);
    }
}
